### ISSUE TITLE
Latin Hypercube dimensionality 

### ISSUE THREAD

**Issue by SanPen** [dme65/sot#2]
Hi,

This is more a conceptual problem that I'd like to understand.

In the past I used the Clensaw-Curtis sampling. This sampling method requires 2^n+1 samples.
I believe that the LatinHypercube is similar in the sense that from 29 dimensions (or so) the sampling points are way to many to be computed.

I have used SOT to test the demo functions with hundreds of variables using Symetric Latin Hyper Cube and it works (at least the computer does not run out of memory)

How do you deal with this in SOT?

Thanks.

**Comment by dme65** [comment]
Latin hypercubes are well-defined for any number of points, so if you work with radial basis functions you only need enough points to uniquely determine the polynomial tail. For a cubic or TPS kernel with a linear tail this is d+1 points (as long as these points aren't linearly dependent). This is how you get away with using an experimental design that depends linearly on the number of dimensions.
