### ISSUE TITLE
citing

### ISSUE THREAD

**Issue by Sandman83** [dme65/sot#3]
Hi! 
Would like to cite you in my Ph.D. I found 
D. Eriksson, D. Bindel, and C. Shoemaker. Surrogate Optimization Toolbox (pySOT). github.com/dme65/pySOT, 2015
on the pySot GitHub site, but nothing on the c++ one. Should I take this? Maybe, a paper arrived in the meantime? ;)

**Comment by dme65** [comment]
Hi there! 
I'm glad you found SOT useful even though I haven't updated it in a while. You can cite it like this: 
"D. Eriksson. Surrogate Optimization Toolbox (SOT). github.com/dme65/SOT, 2016"

**Comment by Sandman83** [comment]
Done :)
